version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -c python:config.gunicorn
        --workers 3
        --log-level=debug
        --access-logfile -
        --reload
        beatthemarket.run_app:app
        run:app
    env_file:
      - '.env'
    volumes:
      - '.:/beatthemarket'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l debug -A beatthemarket.celery_app:app
    env_file:
      - '.env'
    volumes:
      - '.:/beatthemarket'

volumes:
  postgres:
  redis:
